name: MuleSoft CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java (MuleSoft is Java-based)
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      # Step 3: Install Maven (to build the MuleSoft project)
      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          maven-version: '3.8.1'

      # Step 4: Cache Maven dependencies to speed up the build
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 5: Build the MuleSoft project using Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

  # Optionally: You can add a deployment step here when you’re ready
